#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homePage:
    path: /home
    controller: App\Controller\HomeController::homePage

productPage:
    path: /product
    controller: App\Controller\ProductController::productPage

demandePage:
    path: /demande
    controller: App\Controller\DemandeController::demandePage

adminPage:
    path: /admin
    controller: App\Controller\AdminController::adminPage

connectAdminPage:
    path: /connectAdmin
    controller: App\Controller\ConnectAdminController::connectAdminPage

connectAdminCheck:
    path: /connectAdminCheck
    controller: App\Controller\ConnectAdminController::connectAdminCheck
